### ISSUE TITLE
Not IE6-8 Compatible

### ISSUE THREAD

**Issue by newsomderek** [jamiebicknell/Toggle-Switch#8]
I tested your github demo at http://jamiebicknell.github.io/Toggle-Switch/ on Internet Explorer 6, 7 and 8 and the toggle switch doesn't work for all 3. The README states it as IE6+ compatibility.

**Comment by jamiebicknell** [comment]
Hi @newsomderek, I tested when the last major updates were done (~4 years ago) and it worked then for those browsers, so it is a strange one.

Could you state what the exact browser versions were, and the OS version for each one too?

Next week I'll do some tests on those browsers, and let you know what the results were.

**Comment by jamiebicknell** [comment]
Hi @newsomderek, I finally got round to testing this but could only test on IE8 as the Virtual Machine images only go back that far.

I tested using `IE 8.0.7601.17514` and the script worked without any issue.

Therefore I'm closing this issue as it's working in IE8, and as no updates have been made in ~4 years  and IE6-8 worked then, I'm assuming it still works in IE6 and IE7.
